# Generated by Django 3.2.4 on 2021-08-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_hospitallist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitallist',
            old_name='ghph',
            new_name='hospital',
        ),
    ]
