# Generated by Django 3.2.4 on 2021-08-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_rename_ghph_hospitallist_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitallist',
            name='location',
            field=models.TextField(),
        ),
    ]
