# Generated by Django 3.2.4 on 2021-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_covidreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidreport',
            name='activecases',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='covidreport',
            name='totalcases',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='covidreport',
            name='totaldeaths',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='covidreport',
            name='totalrecovered',
            field=models.CharField(max_length=20),
        ),
    ]
